_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

gpt-j:
  source:
    paths:
      - path: gptj-text-generation/
    repository:
      <<: *_gradient_huggingface
      prefix: gptj-text-generation/
  target:
    repository:
      <<: *_common_target_repository
      prefix: ./
